class ObjStorageFilter

class IdObjStorageFilter
class RegexObjStorageFilter
class PrefixObjStorageFilter

class ReadObjStorageFilter

ObjStorageFilter <|-- IdObjStorageFilter
ObjStorageFilter <|-- ReadObjStorageFilter

IdObjStorageFilter <|-- RegexObjStorageFilter
IdObjStorageFilter <|-- PrefixObjStorageFilter
